#!/bin/bash
RED="$(printf '\033[31m')"  
GREEN="$(printf '\033[32m')"  
ORANGE="$(printf '\033[33m')"  
BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"  
CYAN="$(printf '\033[36m')"  
WHITE="$(printf '\033[37m')" 
BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"  
GREENBG="$(printf '\033[42m')"  
ORANGEBG="$(printf '\033[43m')"  
BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"  
CYANBG="$(printf '\033[46m')" 
WHITEBG="$(printf '\033[47m')"
BLACKBG="$(printf '\033[40m')"
RESETBG="$(printf '\e[0m')"
BLINK="$(printf '\033[5;31m')"
echo "$BLUE [1] Kali Linux $RESETBG"
echo "$BLUE [2] Termux$RESETBG"
read -p "$GREEN Choose According to you: $RESETBG" Choose 
if [ $Choose -eq 1 ]; then
  sudo apt install espeak -y
  sudo apt install pv -y
  echo "$GREEN Removing previous file if any...$RESETBG"
  sudo rm -rf /bin/anonymous
  sudo mv Anonymousfr-dbn.sh anonymous
  chmod +x anonymous
  echo "$GREEN Installing... $RESETBG"
  sleep 5
  sudo mv anonymous /bin
  cd ..
  sudo rm -rf Anonymous
  echo "$RED Now run this command $RESETBG"
  echo "$RED anonymous <yourname> $RESETBG"
fi

if [ $Choose -eq 2 ]; then
  PREFIX='/data/data/com.termux/files/usr'
  apt update && apt upgrade -y
  apt install espeak -y
  apt install pv -y
  echo "$GREEN Removing previous file if any...$RESETBG"
  rm -rf $PREFIX/bin/anonymous
  mv Anonymousfr-tmx.sh anonymous
  chmod +x anonymous
  echo "$GREEN Installing...$RESETBG"
  sleep 5
  mv anonymous $PREFIX/bin
  cd ..
  rm -rf Anonymous
  echo "$RED Now run this command $RESETBG"
  echo "$RED anonymous <yourname> $RESETBG"
fi
